config/routes.rb
TwitterApp::Application.routes.draw do

  resources :users
  resources :pages

  get "users/login"
  get "users/signout"
  post "users/authenticate"
  post "users/signup"

  get "pages/home"
  get "pages/own"
  get "pages/others"
  post "pages/create_tweet"
  get "pages/follow"

  match "/login", :to =>"users#login"
  match "/home", :to =>"pages#home"
  match "/own", :to =>"pages#own"
  match "/create_tweet", :to => "pages#create_tweet"
  match "/follow", :to => "pages#follow"
  match "/signout", :to => "users#signout"

end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
attr_accessible :followed_id

belongs_to :follower, :class_name => "User"
belongs_to :followed, :class_name => "User"
end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
 attr_accessible :content
 belongs_to :user
 default_scope :order => 'tweets.created_at DESC'
end

app/models/user.rb
class User < ActiveRecord::Base

attr_accessor :password
attr_accessible :name, :email, :location, :bio, :password

email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

validates :name, :presence => true, :length => { :maximum => 50 }
validates :email, :presence => true, :format => { :with => email_regex }, :uniqueness => { :case_sensitive => false }
validates :password, :presence => true, :length => { :within => 6..40 }


has_many :tweets, :dependent => :destroy

has_many :relationships, :foreign_key => "follower_id", :dependent => :destroy
has_many :following, :through => :relationships, :source => :followed

has_many :reverse_relationships, :foreign_key => "followed_id", :class_name => "Relationship", :dependent => :destroy
has_many :followers, :through => :reverse_relationships, :source => :follower



before_save :encrypt_password

	# Return true if the user's password matches the submitted password.
	def has_password?(submitted_password)
		encrypted_password == encrypt(submitted_password)
	end
	
	def self.authenticate(email, submitted_password)
		user = find_by_email(email)
		return nil if user.nil?
		return user if user.has_password?(submitted_password)
		return nil
	end
	
	def self.authenticate_with_salt(id, cookie_salt)
		user = find_by_id(id)
		return nil if user.nil?
		return user if user.salt == cookie_salt
   end 

private

	def encrypt_password
		self.salt = make_salt if new_record?
		self.encrypted_password = encrypt(password)
	end
	
	def encrypt(string)
		secure_hash("#{salt}--#{string}")
	end
	
	def make_salt
		secure_hash("#{Time.now.utc}--#{password}")
	end
	
	def secure_hash(string)
		Digest::SHA2.hexdigest(string)
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

def create_tweet
  if signed_in?
        @tweet = current_user.tweets.create(params[:tweet]);
  	respond_to do |format|
   	 format.js
 	end
  else
  	redirect_to login_path
  end
end

def follow
  if signed_in?
    respond_to do |format|
       format.js
    end
  else
	redirect_to login_path
  end
end

def home
	if signed_in?
		@title = "Twitter-Home"
		@tweet = Tweet.new
	else
		redirect_to login_path
	end
end

def own
	if signed_in?
		@title ="Twitter-Own"
	else
		redirect_to login_path
	end
end

def edit
	if signed_in?
		@title ="Twitter-Profile"
	else
		redirect_to login_path
	end
end

def show
	if signed_in?
		@title ="Twitter-Profile"
	else
		redirect_to login_path
	end
end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def login
	@title = "Twitter-Login"	
		if signed_in?
			redirect_to home_path	
		else	
			@user = User.new
		end
	end
  
  	def authenticate
				
		@title = "Twitter-home"
		user = User.authenticate(params[:user][:email], params[:user][:password])
		if user.nil?
			redirect_to login_path
		else
			sign_in(user,params[:user][:remember])
			redirect_to home_path
		end
  	end
  
  	def signup
  		user=User.new(params[:user]);
  		if user.save
  			sign_in(user,"")
  			redirect_to home_path
  		else 
  			# The Following defination needs to be changed
  	   	redirect_to login_path
  		end
  	end
  
 	def signout
		sign_out
		redirect_to login_path
	end
  
end

app/helpers/application_helper.rb
module ApplicationHelper

def tweets

	@tweets = [];
	current_user.tweets.each do |tweet|
	   @tweets.push(tweet)
        end

	current_user.following.each do |u|
	   u.tweets.each do |tweet|
		#tweet[username]=u.name;
		@tweets.push(tweet)
	   end
	end
	@tweets.sort_by(&:created_at).reverse

end

end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TwitterApp</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/pages.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%=@title%></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/users.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%=@title%></title>
  <%= stylesheet_link_tag  "style", :media => "all" %>
  <%= stylesheet_link_tag  "front", :media => "all" %>
  <%= javascript_include_tag "jquery-1.7.1.min" %>
  <%= javascript_include_tag "login" %>
  <%= csrf_meta_tags %>
</head>
<body class="login-page">

<%= yield %>

</body>
</html>

app/views/pages/_changepassword.html.erb
<div>
		     <div style="padding-top:12px; padding-left:12px;padding-bottom:4px;"><b><font size=4>Password</font></b></div>
			  <div style="padding-bottom:12px; padding-left:12px;"><font style="color:#999999">Change your password.</font></div>
			</div>
			<form id="change-password" method="POST" action="#">
 			 <div class="tweet-box" style="padding: 9px 12px 9px;">
				  
			 </div>
			 <div class="tweet-box" style="padding: 9px 12px 9px;">
				  
			 </div>	
			</form>

app/views/pages/_editprofile.html.erb
 <div>
		     <div style="padding-top:12px; padding-left:12px;padding-bottom:4px;"><b><font size=4>Profile</font></b></div>
			  <div style="padding-bottom:12px; padding-left:12px;"><font style="color:#999999">This Information appears on your public profile, search results, and beyond.</font></div>
			</div>
			<form id="profile-form" method="POST" action="#">
 			 <div class="tweet-box" style="padding: 9px 12px 9px;">
				  
			 </div>
			 <div class="tweet-box" style="padding: 9px 12px 9px;">
				  <label for="name">Name</label><div class="text-area"><input class="tweet-textarea" type="text" id="name" /></div>
				  <label for="location">Location</label><div class="text-area"><input class="tweet-textarea" type="text" id="location" /></div>
				  <label for="website">Website</label><div class="text-area"><input class="tweet-textarea" type="text" id="website" /></div>
				  <label for="bio">Bio</label><div class="text-area"><input class="tweet-textarea" type="text" id="bio" /></div>
			 </div>	
 		    <div class="tweet-box" style="padding: 9px 12px 9px;">
				  <div align="center"><button id="settings_save" class="btn-highlighted" type="submit">Save changes</button></div>
			 </div>
			</form>

app/views/pages/_followers.html.erb
                         <div class="tweet-box" >
				<div style="padding: 9px 12px 9px;">
				  <table bordar="none">
					<tr VALIGN=TOP>     
					 <td style="valign:top;">					
					<%follower_image = image_tag("BGtwitter_normal.JPG", :width=>"60px",:height=>"60px", :class=>"profile-image") %>
                                        <%=link_to follower_image,"#" %>
 
				    </td>
				    <td style="width:340px; padding-left:8px;">
				       <a href="#">
			 	 	 	   Bill Gates 
		 		        </a>
		 		        <small>@billgates</small>
		 		        <div></div>
					 </td>
					 <td>
					   <%=link_to "Follow","#",:class=>"follow-btn"%>
					 </td>
					</tr>
		 		  </table>
				</div>
			</div>
			<div class="tweet-box" >
				<div style="padding: 9px 12px 9px;">
				  <table bordar="none">
					<tr VALIGN=TOP>     
					 <td style="valign:top;">					
					<%follower_image = image_tag("BGtwitter_normal.JPG", :width=>"60px",:height=>"60px", :class=>"profile-image") %>
                                        <%=link_to follower_image,"#" %>
				    </td>
				    <td style="width:340px; padding-left:8px;">
				       <a href="#">
			 	 	 	   Bill Gates 
		 		        </a>
		 		        <small>@billgates</small>
		 		        <div></div>
					 </td>
					 <td>
					   <%=link_to "Following","#",:class=>"following-btn"%>
					 </td>
					</tr>
		 		  </table>
				</div>
			</div>

app/views/pages/_following.html.erb
			<div class="tweet-box" >
				<div style="padding: 9px 12px 9px;">
				  <table bordar="none">
					<tr VALIGN=TOP>     
					 <td style="valign:top;">
                                           <%following_image=image_tag("BGtwitter_normal.JPG", :width=>"60px", :height=>"60px",:class=>"profile-image")%>
					   <%=link_to following_image,"#" %>
				    </td>
				    <td style="width:340px; padding-left:8px;">
				       <a href="#">
			 	 	 	   Bill Gates 
		 		        </a>
		 		        <small>@billgates</small>
		 		        <div></div>
					 </td>
					 <td>
					   <%=link_to "Following","#",:class=>"following-btn"%>
					 </td>
					</tr>
		 		  </table>
				</div>
			</div>

app/views/pages/_menu.html.erb
<div id="menu">
	<div>
	<table VALIGN=MIDDLE height="100%" width="100%">
		<tr><td>
                 <%home_icon=image_tag("home.png", :alt=>"Home", :width=>"32", :height=>"32")%>
                 <%=link_to home_icon, home_path %>
                 <small style="color:white"><b>Home</b></small></a>
                   </td>
                   <td width="700px"></td>
                   <td>
                   <%=image_tag("man-icon.png", :id=>"profile-button", :width=>"32",:height=>"32")%>
                </td></tr>
	 </table>
	</div>
</div>

app/views/pages/_profile-popup.html.erb
<div id="profile-popup" class="drop-down-menu">
	<div style="padding: 5px 20px 5px;">
			 <table>
   		  <tr border="none" VALIGN=TOP>
				<td>
 				  <div>
				      <%=image_tag("default_profile_0_normal.png", :class=>"profile-image", :style=>"width: 32px; height: 32px;")%>
				   </div>
				</td>
				<td colspan="2" style=" padding-left:8px;">
				
 				  <div style="font-size:12px">
                                    <%=link_to "Nagesh Vanam",own_path%>
                                  </div>
 				 
 				  <small style="color:#999999">View my profile page</small>
    			</td>
			  </tr>
   		  <tr border="none" VALIGN=TOP>
				<td width="10px">
 				  
				</td>
				<td colspan="2" style=" padding-left:8px;">
				<%=link_to "Lagout",signout_path%>
    			</td>
			  </tr>
			 </table>
	</div>
</div>

app/views/pages/_suggestbox.html.erb
<div class="tweet-box" >
	<div style="padding: 9px 12px 9px;">
		<table bordar="none">
		 <tr VALIGN=TOP>
			<td style="valign:top;">
                	 <%suggest_image = image_tag("BGtwitter_normal.JPG", :width=>"60px", :height=>"60px", :class=>"profile-image")%>
	     		 <%=link_to suggest_image, "#" %>
			</td>
			<td style=" padding-left:8px;">
			 <small>				       
	 		  <a href="#">
			   Bill Gates @billgates
			  </a>
		 	  <div>Followed by Nagesh Vanam and others</div>
		 	  <div><%=link_to "Follow", follow_path, :class=>"follow-link", :style=>"color:#009ee0", :remote=>true%></div>
		 	 </small>
		        </td>
		</tr>
	       </table>
	</div>
</div>

app/views/pages/_tweetbox.html.erb
<%tweets.each do |tweet|%>
<div class="tweet-box">
     <div style="padding: 9px 12px 9px;">
	 <table bordar="none" width="100%">
	<tr VALIGN=TOP>
	 <td rowspan="2" width="45px">
          <%tweet_img=image_tag("BGtwitter_normal.JPG", :width=>"60px", :height=>"60px", :class=>"profile-image") %>			
	  <%=link_to tweet_img,page_path(tweet.user) %>
	 </td>
	 <td style=" padding-left:8px;">
	  <%=link_to tweet.user.name,page_path(tweet.user) %>
	 </td>
         <td>
	    <div>
		<%if tweet.user == current_user%>
			<%=link_to "delete","#"%>
		<%end%>
	    </div>
	 </td>
	 <td align="right"><small style="color:gray"><%=time_ago_in_words(tweet.created_at)%></small></td>
        </tr>
        <tr>
         <td colspan="3" style=" padding-left:8px;">
           <%=tweet.content%>
         </td>
        </tr>
  </table>
 </div>
</div>
<%end%>

app/views/pages/create_tweet.js.erb
 $(htmlText()).insertAfter($("#tweets h2")).fadeIn(500, function(){
				$("#char-count").css("display","block");
			   $("#char-count").prev().css("display","none");
				$("#tweet").removeClass("expanded");
				$("#tweet").removeAttr("style");
				$("#tweet").val("Compose new Tweet...");
				$("#tweet").parent().next().css("display","none");
    		    $("#btn-tweet").removeClass("btn-highlighted").addClass("btn");
				$("#char-count").html(140);
			 });

$("#count-box td:nth-child(1) div:first").html(<%=current_user.tweets.count%>);

 function htmlText(){
 <%tweet_img=image_tag("BGtwitter_normal.JPG", :width=>"60px", :height=>"60px", :class=>"profile-image") %>			

    	return '<div style="display:none" class="tweet-box" ><div style="padding: 9px 12px 9px;"><table width="100%" bordar="none"><tr VALIGN=TOP><td  rowspan="2" width="45px" rowspan="2"><%=link_to tweet_img,page_path(@tweet.user)%></td><td style=" padding-left:8px;"><%=link_to @tweet.user.name,page_path(@tweet.user) %></td><td><%if @tweet.user == current_user%><%=link_to "delete","#"%><%end%></td> <td align="right"><small style="color:gray"><%=time_ago_in_words(@tweet.created_at)%></small></td></tr><tr><td colspan="3" style=" padding-left:8px;"><%=@tweet.content%></td></tr></table></div></div>';

    }

app/views/pages/edit.html.erb
<%=render "menu"%>
<%=render "profile-popup"%>
<div id="container">
	<div class="dashboard">
   	<div class="round-box">
			<div style="padding: 10px 10px 10px;">
			 <table >
   		  <tr border="none" VALIGN=TOP>
				<td>
 				  <div>
  				     <%=image_tag("default_profile_0_normal.png",:style=>"width: 32px;	height: 32px;",:class=>"profile-image") %>
				   </div>
				</td>
				<td colspan="2" style=" padding-left:8px;">
				  <div><%=link_to "Nagesh Vanam",own_path %></div>
 				  <small style="color:#999999">View my profile page</small>
    			</td>
			  </tr>
			 </table>
			</div>
		</div>
   	<div id="profile-page" class="round-box">
			 <div class="tweet-box own-link selected" style="border-top:0px; padding-left:10px;padding-right:10px;padding-top:6px;padding-bottom:6px;color:black;">Profile</div>
			 <div class="tweet-box own-link" style="padding-left:10px;padding-right:10px;padding-top:6px;padding-bottom:6px;">Password</div>
			 <div class="tweet-box own-link" style="padding-left:10px;padding-right:10px;padding-top:6px;padding-bottom:6px;">Design</div>
		</div>
   	<div class="round-box">
			tweets<br/>
			tweets<br/>
			tweets<br/>
			tweets<br/>
			tweets<br/>
			tweets<br/>
			tweets<br/>
		</div>
	</div>
	<div class="content">
		<div class="round-box" style="display:block" id="profile">
			<%=render "editprofile" %>
		</div>
		<div class="round-box" style="display:none" id="password">
			<%=render "changepassword" %>
		</div>
		<div class="round-box" style="display:none" id="design">
			<%=render "design" %>
		</div>
	</div>
	<div class="footer" />
</div>
</body>

app/views/pages/home.html.erb
<%=render "menu"%>
<%=render "profile-popup"%>

<div id="container">
	<div class="dashboard">
   	<div id="mini-profile" class="round-box">
			<div style="padding: 10px 10px 10px;">
			 <table >
   		  <tr border="none" VALIGN=TOP>
				<td>
 				  <div>
				     <%=image_tag("default_profile_0_normal.png",:style=>"width: 32px; height: 32px;",:class=>"profile-image")%>
				   </div>
				</td>
				<td colspan="2" style=" padding-left:8px;">
				  
 				   <div><%=link_to current_user.name,own_path %></div>
 				  
 				 <small style="color:#999999">View my profile page</small>
    			</td>
			  </tr>
			 </table>
			</div>
			
			<div class="tweet-box">
			 <table id="count-box" width="100%" cellspacing="0">
   		  <tr VALIGN=TOP>
				<td width="20%" style="padding:4px 10px 4px 10px">
 				  <div style="font-size: 14px;"><b><%=current_user.tweets.count%></b></div>
 				  <div style="color: #999;font-size: 10px;line-height: 16px;text-transform: uppercase;">Tweet
 				  </div>
				</td>
				<td bgcolor="#dddddd"></td>
				<td width="30%" style="padding:4px 10px 4px 10px">
				  <div style="font-size: 14px;"><b><%=current_user.following.count%></b></div>
 				  <div style="color: #999;font-size: 10px;line-height: 16px;text-transform: uppercase;">Following
 				  </div>
				</td>
				<td bgcolor="#dddddd"></td>
				<td  width="50%" style="padding:4px 10px 4px 10px">
				  <div style="font-size: 14px;"><b><%=current_user.followers.count%></b></div>
 				  <div style="color: #999;font-size: 10px;line-height: 16px;text-transform: uppercase;">Followers
 				  </div>
				</td>
			  </tr>
			 </table>
			</div>
			
			<div style="padding: 10px 10px 10px;" class="tweet-box">


					<%= form_for @tweet,:url => {:action => "create_tweet" }, :remote => true do |f| %>


			 		<div class="text-area">
						  <%= f.text_area :content, :rows=>"1", :id=>"tweet", :class=>"tweet-textarea", :value=>"Compose new Tweet..." %>
			 		</div>
			 		<div style="display:none">
			 		<table style="padding-top: 12px;" border="0" cellspacing="0" cellpadding="0">
			 			<tr align="right">
			 			<td width="230px" style="padding-right:8px">
						<%=image_tag("img.gif", :style=>"display:none;") %>
			 			<div id="char-count" style="color: #999;font-size: 14px;line-height: 16px;text-transform: uppercase;">140</div>
			 			</td>
			 			<td>
			  			<%= f.submit "Tweet", :id=>"btn-tweet", :style=>"color:#000000; text-decoration:none;", :class=>"btn"%>
			 			</td>
			 			</tr>
			 		</table>
			 		</div>
			 		<% end %>
			</div>
			
		</div>
   	<div id="suggestion-box"  class="round-box">
   	   <h3 style="margin-left:8px">Who to Follow</h3>
	   <%=render "suggestbox"%>
	</div>
	</div>
	<div class="content">
		<div class="round-box" id="tweets">
			<div><h2>&nbsp&nbspTweets</h2></div>
			<%=render "tweetbox"%>		
		</div>
	</div>
	 <div class="footer" />
</div>
</body>

app/views/pages/profile.html.erb
<%=render "menu"%>
<%=render "profile-popup"%>
<div id="container">
	<div class="dashboard">
   	<div class="round-box">
			<div style="padding: 10px 10px 10px;">
			 <table >
   		  <tr border="none" VALIGN=TOP>
				<td>
 				  <div>
  				     <%=image_tag("default_profile_0_normal.png",:style=>"width: 32px;	height: 32px;",:class=>"profile-image") %>
				   </div>
				</td>
				<td colspan="2" style=" padding-left:8px;">
				  <div><%=link_to "Nagesh Vanam",own_path %></div>
 				  <small style="color:#999999">View my profile page</small>
    			</td>
			  </tr>
			 </table>
			</div>
		</div>
   	<div id="profile-page" class="round-box">
			 <div class="tweet-box own-link selected" style="border-top:0px; padding-left:10px;padding-right:10px;padding-top:6px;padding-bottom:6px;color:black;">Profile</div>
			 <div class="tweet-box own-link" style="padding-left:10px;padding-right:10px;padding-top:6px;padding-bottom:6px;">Password</div>
			 <div class="tweet-box own-link" style="padding-left:10px;padding-right:10px;padding-top:6px;padding-bottom:6px;">Design</div>
		</div>
   	<div class="round-box">
			tweets<br/>
			tweets<br/>
			tweets<br/>
			tweets<br/>
			tweets<br/>
			tweets<br/>
			tweets<br/>
		</div>
	</div>
	<div class="content">
		<div class="round-box" style="display:block" id="profile">
			<%=render "editprofile" %>
		</div>
		<div class="round-box" style="display:none" id="password">
			<%=render "changepassword" %>
		</div>
		<div class="round-box" style="display:none" id="design">
			<%=render "design" %>
		</div>
	</div>
	<div class="footer" />
</div>
</body>

app/views/pages/show.html.erb
<%=render "menu"%>
<%=render "profile-popup"%>
<div id="container">
	<div class="round-box" id="acc-header">
		<table style="padding:10px">
			<tr VALIGN=TOP>
				<td><%=image_tag("default_profile_add_photo.png", :style=>"width: 128px; height: 128px;",:class=>"profile-image") %></td>
				<td width="535px" style="padding-left:8px"><b style="font-size:1.8em;">nagesh</b><div  style="color:gray;">@ngshvanam</div></td>
				<td>
					<%=link_to "Edit Your Profile",edit_page_path(current_user) ,:style=>"color:#000000; text-decoration:none;",:class=>"edit-profile-btn" %>
					<table height="100%" width="100%" style="padding-top:10px;" >
					<tr >
						<td style="padding-bottom:4px">
							<div style="font-size: 14px;"><b>237</b>&nbsp;<span onclick="$('#own-page :nth-child(1)').click()" style="color: #999;font-size: 10px;line-height: 16px;text-transform: uppercase;">Tweet</span></div>			
						</td>
					</tr>
					<tr height="1" bgcolor="#dddddd">
					  <td></td>
					</tr>
					<tr >
					  <td style="padding-top:4px; padding-bottom:4px">
					  		<div style="font-size: 14px;"><b>98</b>&nbsp;<span onclick="$('#own-page :nth-child(2)').click()" style="color: #999;font-size: 10px;line-height: 16px;text-transform: uppercase;">Following</span></div>
					  </td>
					</tr>
					<tr height="1"  bgcolor="#dddddd">
					  <td></td>
					</tr>
					<tr >
					  <td style="padding-top:4px; padding-bottom:4px">
					  		<div style="font-size: 14px;"><b>156</b>&nbsp;<span onclick="$('#own-page :nth-child(3)').click()" style="color: #999;font-size: 10px;line-height: 16px;text-transform: uppercase;">Followers</span></div>
					  </td>
					</tr>
					</table>
				</td>
			</tr>		
		</table>
	</div>
	<div class="dashboard">
   	<div id="own-page" class="round-box">
			<div class="tweet-box own-link selected" style="border-top:0px; padding-left:10px;padding-right:10px;padding-top:6px;padding-bottom:6px;color:black">Tweets</div>
			<div class="tweet-box own-link" style="padding-left:10px;padding-right:10px;padding-top:6px;padding-bottom:6px;">Following</div>
			<div class="tweet-box own-link" style="padding-left:10px;padding-right:10px;padding-top:6px;padding-bottom:6px;">Followers</div>
			<div class="tweet-box own-link" style="padding-left:10px;padding-right:10px;padding-top:6px;padding-bottom:6px;">Favorites</div>
			<div class="tweet-box own-link" style="padding-left:10px;padding-right:10px;padding-top:6px;padding-bottom:6px;">Lists</div>
		</div>
   	<div class="round-box">
			tweets<br/>
			tweets<br/>
			tweets<br/>
			tweets<br/>
			tweets<br/>
			tweets<br/>
			tweets<br/>
		</div>
	</div>
	<div class="content">
		<div class="round-box" id="tweets">
		    <h2>&nbsp&nbspTweets</h2>
			<%=render "tweetbox"%>
			<%=render "tweetbox"%>
			<%=render "tweetbox"%>
			<%=render "tweetbox"%>
			<%=render "tweetbox"%>
			<%=render "tweetbox"%>
			<%=render "tweetbox"%>
			<%=render "tweetbox"%>
			<%=render "tweetbox"%>
			<%=render "tweetbox"%>		
			
		</div>
		<div class="round-box" style="display:none" id="following">
			<h2>&nbsp&nbspFollowing</h2>
			<%=render "following"%>
			<%=render "following"%>
		</div>
		<div class="round-box" style="display:none" id="followers">
			<h2>&nbsp&nbspFollowers</h2>
			<%=render "followers"%>
		</div>
		<div class="round-box" style="display:none" id="favorites">
			<h2>&nbsp;&nbsp;Favourites</h2>
		</div>
		<div class="round-box" style="display:none" id="lists">
			<h2>&nbsp;&nbsp;Lists</h2>
		</div>
	</div>
	<div class="footer" />
</div>